name: elm

on: 
  push:
    branches: 
      - master

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: justgook/setup-elm@1.2.0
    - run: elm make src/Main.elm --optimize --output=dist/index.html
    - run: mv src/css dist/css
    - uses: JamesIves/github-pages-deploy-action@3.6.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
